[package]
name = "rust-norg"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.9.3"
clap = { version = "4.5.4", features = ["derive"] }
eyre = "0.6.12"
itertools = "0.13.0"

[dev-dependencies]
insta = "1.39.0"
